version: '3'
services:
  api:
    image: pfr/api:latest
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db/postgres-data:/var/lib/postgresql/data

  worker:
    image: pfr/worker:latest
    depends_on:
      - redis
      - postgres

  redis:
      image: "redis:alpine"
